# For more information on these settings, please refer to the ReadMe file!
proteome_fasta: # If this is set, R1, R2 and transcriptome MUST NOT be set.
R1:
R2: # only set if your reads are paired-end
transcriptome:
toxin_db:
basename: ""
contaminants:
contamination_evalue: 1E-5
clustering_threshold: 0.99
cys_pattern: False
maxlen: 45000
memory: # maximum memory in GigaByte
minlen: 99
mmseqs_sequence_coverage: 0.0
mmseqs_path:
output_dir: output
pfam_db_path:
quant: False
repeated_aa_threshold: 5
signalpeptide_minlen: 10
swissprot: False
swissprot_evalue: 1E-10
swissprot_db_path:
threads: # logic threads
tmbed_model_path:
tmbed_use_cpu: True
tmbed_use_gpu: True
toxins_evalue: 1E-10
TPMthreshold: 1000
wolfpsort: False
wolfPsort_path: