"""
This module bundles the peptide filtering rules

filter_signalp_outputs <- extract_secreted_peptides <- run_phobius <- extract_non_tM_peptides

together with the toxin filtering rules

retrieve_orfs_with_blast_without_signalp <- retrieve_candidate_toxins.

Its public API consists of the outputs of retrieve_candidate_toxins and filter_signalp_outputs.
"""
import subprocess
import tempfile
from functools import cache
from pathlib import Path

import pandas as pd
from Bio import SeqIO

from lib import config, utils
from lib.utils import global_output

__all__ = ["retrieve_candidate_toxins"]


# ============================= Public functions ============================= #
@cache
def retrieve_candidate_toxins(clustered_peptides: Path, toxins_blast_result: pd.DataFrame,
                              signalp_result: pd.DataFrame) -> Path:
    """
    Builds a list of toxin candidates out of the data provided with the parameters.
    :param clustered_peptides: A FASTA file containing amino acid sequences.
    :param toxins_blast_result: A DataFrame containing peptides without any signal sequence.
    :param signalp_result: A DataFrame containing peptides with clear signal sequences.
    :return: A DataFrame holding those sequences that are candidate toxins.
    """
    secreted_peptides, non_secreted_peptides = _extract_secreted_peptides(signalp_result, clustered_peptides)
    phobius_result = _run_phobius(secreted_peptides)

    output_file = utils.global_output(config.get("basename") + "_candidate_toxins.fasta")

    with open(output_file, "w") as out_file:
        for seq in pd.concat((_filter_fasta_file(secreted_peptides, phobius_result),
                              _filter_fasta_file(non_secreted_peptides, toxins_blast_result))).iterrows():
            SeqIO.write(seq[1].iloc[0], out_file, "fasta")

    return output_file


# ============================ Private functions ============================= #
def _extract_secreted_peptides(signalp_result: pd.DataFrame, clustered_peptides: Path) -> tuple[Path, Path]:
    """
    This function filters a FASTA file with amino acid sequences against the SignalP output and
    sorts them into 'secreted' and 'non-secreted' peptides.
    :param signalp_result: The filtered output of SignalP with only the definitively secreted peptides included.
    :param clustered_peptides: The path to a FASTA file containing amino acid sequences (e.g. the output of `cluster_peptides`).
    :return: A tuple of two file paths with the first one pointing to the secreted peptides and the second one pointing to the non-secreted peptides.
    """
    secreted_peptides = global_output(config.get("basename") + "_secreted_peptides.fasta")
    non_secreted_peptides = global_output(config.get("basename") + "_non_secreted_peptides.fasta")

    with open(non_secreted_peptides, "w") as n_outfile, open(secreted_peptides, "w") as out_file:
        for seq in SeqIO.parse(clustered_peptides, "fasta"):
            if seq.id in signalp_result.index:
                SeqIO.write(seq, out_file, "fasta")
            else:
                SeqIO.write(seq, n_outfile, "fasta")

    return secreted_peptides, non_secreted_peptides


def _run_phobius(secreted_peptides: Path) -> pd.DataFrame:
    """
    Runs Phobius.
    :param secreted_peptides: The path to a FASTA file containing secreted peptides as generated by e.g. `_extract_secreted_peptides`.
    :return: A DataFrame with the results from Phobius.
    """
    with tempfile.NamedTemporaryFile(suffix=".tsv", delete_on_close=False) as table:
        subprocess.run(
            f"phobius.pl -short {secreted_peptides} | sed 's/\\s\\+/\\t/g' | awk '$2 == 0' > {table}"
        )

        return pd.read_csv(table, sep="\\s+", index_col=0)


def _filter_fasta_file(fasta_file: Path, filter_map: pd.DataFrame) -> pd.DataFrame:
    """
    Filters a FASTA file for the peptides present in the file given by the second parameter.
    All peptides in the first file, that are also present in the second file,
    will be copied into a pandas DataFrame and returned.

    :param fasta_file: The path to the FASTA file that shall be filtered.
    :param filter_map: The path to a TSV file providing the IDs of the peptides to be kept.
    :return: A DataFrame containing the peptides present in both files.
    """

    records = utils.fasta_to_dataframe(fasta_file).set_index("ID")
    return records.drop(records.join(filter_map, how="left_anti", rsuffix="_filter").index)
